/*
 * API Sprint - Documentazione
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.ibswebco.sprint;

import it.ibswebco.spint.ApiException;
import org.openapitools.client.model.InlineObject;
import org.openapitools.client.model.InlineObject1;
import org.openapitools.client.model.V2modelliStoreRequest;
import org.openapitools.client.model.V2modelliUpdateRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ModelloApi
 */
@Disabled
public class ModelloApiTest {

    private final ModelloApi api = new ModelloApi();

    /**
     * Remove the specified resource from storage
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v2modelliDestroyTest() throws ApiException {
        Integer modello = null;
        api.v2modelliDestroy(modello);
        // TODO: test validations
    }

    /**
     * Display a listing of the resource
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v2modelliIndexTest() throws ApiException {
        Object response = api.v2modelliIndex();
        // TODO: test validations
    }

    /**
     * Display the specified resource
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v2modelliShowTest() throws ApiException {
        Integer modello = null;
        Object response = api.v2modelliShow(modello);
        // TODO: test validations
    }

    /**
     * Store a newly created resource in storage
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v2modelliStoreTest() throws ApiException {
        V2modelliStoreRequest v2modelliStoreRequest = null;
        Object response = api.v2modelliStore(v2modelliStoreRequest);
        // TODO: test validations
    }

    /**
     * Update the specified resource in storage
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v2modelliUpdateTest() throws ApiException {
        Integer modello = null;
        V2modelliUpdateRequest v2modelliUpdateRequest = null;
        Object response = api.v2modelliUpdate(modello, v2modelliUpdateRequest);
        // TODO: test validations
    }

}
