/*
 * API Sprint - Documentazione
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.ibswebco.sprint;

import it.ibswebco.spint.ApiException;
import org.openapitools.client.model.InlineObject;
import org.openapitools.client.model.InlineObject1;
import org.openapitools.client.model.V2richiesteStoreRequest;
import org.openapitools.client.model.V2richiesteUpdateRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RichiestaApi
 */
@Disabled
public class RichiestaApiTest {

    private final RichiestaApi api = new RichiestaApi();

    /**
     * Remove the specified resource from storage
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v2richiesteDestroyTest() throws ApiException {
        String richiesta = null;
        Object response = api.v2richiesteDestroy(richiesta);
        // TODO: test validations
    }

    /**
     * Display a listing of the resource
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v2richiesteIndexTest() throws ApiException {
        Object response = api.v2richiesteIndex();
        // TODO: test validations
    }

    /**
     * Display the specified resource
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v2richiesteShowTest() throws ApiException {
        String richiesta = null;
        Object response = api.v2richiesteShow(richiesta);
        // TODO: test validations
    }

    /**
     * Store a newly created resource in storage
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v2richiesteStoreTest() throws ApiException {
        V2richiesteStoreRequest v2richiesteStoreRequest = null;
        Object response = api.v2richiesteStore(v2richiesteStoreRequest);
        // TODO: test validations
    }

    /**
     * Update the specified resource in storage
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v2richiesteUpdateTest() throws ApiException {
        String richiesta = null;
        V2richiesteUpdateRequest v2richiesteUpdateRequest = null;
        Object response = api.v2richiesteUpdate(richiesta, v2richiesteUpdateRequest);
        // TODO: test validations
    }

}
