/*
 * API Sprint - Documentazione
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package it.ibswebco.sprint;

import it.ibswebco.spint.ApiException;
import org.openapitools.client.model.InlineObject;
import org.openapitools.client.model.InlineObject1;
import org.openapitools.client.model.V2vistiStoreRequest;
import org.openapitools.client.model.V2vistiUpdateRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VistoApi
 */
@Disabled
public class VistoApiTest {

    private final VistoApi api = new VistoApi();

    /**
     * Remove the specified resource from storage
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v2vistiDestroyTest() throws ApiException {
        String visto = null;
        api.v2vistiDestroy(visto);
        // TODO: test validations
    }

    /**
     * Display a listing of the resource
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v2vistiIndexTest() throws ApiException {
        Object response = api.v2vistiIndex();
        // TODO: test validations
    }

    /**
     * Display the specified resource
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v2vistiShowTest() throws ApiException {
        String visto = null;
        Object response = api.v2vistiShow(visto);
        // TODO: test validations
    }

    /**
     * Store a newly created resource in storage
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v2vistiStoreTest() throws ApiException {
        V2vistiStoreRequest v2vistiStoreRequest = null;
        Object response = api.v2vistiStore(v2vistiStoreRequest);
        // TODO: test validations
    }

    /**
     * Update the specified resource in storage
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void v2vistiUpdateTest() throws ApiException {
        String visto = null;
        V2vistiUpdateRequest v2vistiUpdateRequest = null;
        Object response = api.v2vistiUpdate(visto, v2vistiUpdateRequest);
        // TODO: test validations
    }

}
