/*
 * API Sprint - Documentazione
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V2modelliUpdateRequest
 */
public class V2modelliUpdateRequestTest {
    private final V2modelliUpdateRequest model = new V2modelliUpdateRequest();

    /**
     * Model tests for V2modelliUpdateRequest
     */
    @Test
    public void testV2modelliUpdateRequest() {
        // TODO: test V2modelliUpdateRequest
    }

    /**
     * Test the property 'descrizione'
     */
    @Test
    public void descrizioneTest() {
        // TODO: test descrizione
    }

    /**
     * Test the property 'speditore'
     */
    @Test
    public void speditoreTest() {
        // TODO: test speditore
    }

    /**
     * Test the property 'destinatario'
     */
    @Test
    public void destinatarioTest() {
        // TODO: test destinatario
    }

    /**
     * Test the property 'trasporto'
     */
    @Test
    public void trasportoTest() {
        // TODO: test trasporto
    }

    /**
     * Test the property 'osservazioni'
     */
    @Test
    public void osservazioniTest() {
        // TODO: test osservazioni
    }

    /**
     * Test the property 'paeseDestinazione'
     */
    @Test
    public void paeseDestinazioneTest() {
        // TODO: test paeseDestinazione
    }

    /**
     * Test the property 'aziendaProduttrice'
     */
    @Test
    public void aziendaProduttriceTest() {
        // TODO: test aziendaProduttrice
    }

    /**
     * Test the property 'aziendaModifiche'
     */
    @Test
    public void aziendaModificheTest() {
        // TODO: test aziendaModifiche
    }

    /**
     * Test the property 'documentazioneAllegata'
     */
    @Test
    public void documentazioneAllegataTest() {
        // TODO: test documentazioneAllegata
    }

    /**
     * Test the property 'giacenzaMerci'
     */
    @Test
    public void giacenzaMerciTest() {
        // TODO: test giacenzaMerci
    }

    /**
     * Test the property 'ncopie'
     */
    @Test
    public void ncopieTest() {
        // TODO: test ncopie
    }

    /**
     * Test the property 'nvisti'
     */
    @Test
    public void nvistiTest() {
        // TODO: test nvisti
    }

    /**
     * Test the property 'nleg'
     */
    @Test
    public void nlegTest() {
        // TODO: test nleg
    }

    /**
     * Test the property 'fattFirmata'
     */
    @Test
    public void fattFirmataTest() {
        // TODO: test fattFirmata
    }

    /**
     * Test the property 'notecciaa'
     */
    @Test
    public void notecciaaTest() {
        // TODO: test notecciaa
    }

}
