/*
 * API Sprint - Documentazione
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.V2richiesteStoreRequestCciaa;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V2richiesteUpdateRequest
 */
public class V2richiesteUpdateRequestTest {
    private final V2richiesteUpdateRequest model = new V2richiesteUpdateRequest();

    /**
     * Model tests for V2richiesteUpdateRequest
     */
    @Test
    public void testV2richiesteUpdateRequest() {
        // TODO: test V2richiesteUpdateRequest
    }

    /**
     * Test the property 'descrizione'
     */
    @Test
    public void descrizioneTest() {
        // TODO: test descrizione
    }

    /**
     * Test the property 'speditore'
     */
    @Test
    public void speditoreTest() {
        // TODO: test speditore
    }

    /**
     * Test the property 'destinatario'
     */
    @Test
    public void destinatarioTest() {
        // TODO: test destinatario
    }

    /**
     * Test the property 'paeseOrigine'
     */
    @Test
    public void paeseOrigineTest() {
        // TODO: test paeseOrigine
    }

    /**
     * Test the property 'informazioni'
     */
    @Test
    public void informazioniTest() {
        // TODO: test informazioni
    }

    /**
     * Test the property 'osservazioni'
     */
    @Test
    public void osservazioniTest() {
        // TODO: test osservazioni
    }

    /**
     * Test the property 'paeseDest'
     */
    @Test
    public void paeseDestTest() {
        // TODO: test paeseDest
    }

    /**
     * Test the property 'numeroCopie'
     */
    @Test
    public void numeroCopieTest() {
        // TODO: test numeroCopie
    }

    /**
     * Test the property 'trasporto'
     */
    @Test
    public void trasportoTest() {
        // TODO: test trasporto
    }

    /**
     * Test the property 'merci'
     */
    @Test
    public void merciTest() {
        // TODO: test merci
    }

    /**
     * Test the property 'quantita'
     */
    @Test
    public void quantitaTest() {
        // TODO: test quantita
    }

    /**
     * Test the property 'valoreMerce'
     */
    @Test
    public void valoreMerceTest() {
        // TODO: test valoreMerce
    }

    /**
     * Test the property 'numeroAut'
     */
    @Test
    public void numeroAutTest() {
        // TODO: test numeroAut
    }

    /**
     * Test the property 'paeseComunitario'
     */
    @Test
    public void paeseComunitarioTest() {
        // TODO: test paeseComunitario
    }

    /**
     * Test the property 'produzione'
     */
    @Test
    public void produzioneTest() {
        // TODO: test produzione
    }

    /**
     * Test the property 'aziendaProduttrice'
     */
    @Test
    public void aziendaProduttriceTest() {
        // TODO: test aziendaProduttrice
    }

    /**
     * Test the property 'modifiche'
     */
    @Test
    public void modificheTest() {
        // TODO: test modifiche
    }

    /**
     * Test the property 'aziendaModifiche'
     */
    @Test
    public void aziendaModificheTest() {
        // TODO: test aziendaModifiche
    }

    /**
     * Test the property 'paeseExtraue'
     */
    @Test
    public void paeseExtraueTest() {
        // TODO: test paeseExtraue
    }

    /**
     * Test the property 'documentazioneAllegata'
     */
    @Test
    public void documentazioneAllegataTest() {
        // TODO: test documentazioneAllegata
    }

    /**
     * Test the property 'giacenzaMerci'
     */
    @Test
    public void giacenzaMerciTest() {
        // TODO: test giacenzaMerci
    }

    /**
     * Test the property 'annotazioniMittente'
     */
    @Test
    public void annotazioniMittenteTest() {
        // TODO: test annotazioniMittente
    }

    /**
     * Test the property 'annotazioniInterne'
     */
    @Test
    public void annotazioniInterneTest() {
        // TODO: test annotazioniInterne
    }

    /**
     * Test the property 'proforma'
     */
    @Test
    public void proformaTest() {
        // TODO: test proforma
    }

    /**
     * Test the property 'urgente'
     */
    @Test
    public void urgenteTest() {
        // TODO: test urgente
    }

    /**
     * Test the property 'emailContatto'
     */
    @Test
    public void emailContattoTest() {
        // TODO: test emailContatto
    }

    /**
     * Test the property 'cciaa'
     */
    @Test
    public void cciaaTest() {
        // TODO: test cciaa
    }

}
