/*
 * API Sprint - Documentazione
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V2richiesteStoreRequestCciaa
 */
public class V2richiesteStoreRequestCciaaTest {
    private final V2richiesteStoreRequestCciaa model = new V2richiesteStoreRequestCciaa();

    /**
     * Model tests for V2richiesteStoreRequestCciaa
     */
    @Test
    public void testV2richiesteStoreRequestCciaa() {
        // TODO: test V2richiesteStoreRequestCciaa
    }

    /**
     * Test the property 'sportello'
     */
    @Test
    public void sportelloTest() {
        // TODO: test sportello
    }

    /**
     * Test the property 'sede'
     */
    @Test
    public void sedeTest() {
        // TODO: test sede
    }

}
