/*
 * API Sprint - Documentazione
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V2vistiUpdateRequest
 */
public class V2vistiUpdateRequestTest {
    private final V2vistiUpdateRequest model = new V2vistiUpdateRequest();

    /**
     * Model tests for V2vistiUpdateRequest
     */
    @Test
    public void testV2vistiUpdateRequest() {
        // TODO: test V2vistiUpdateRequest
    }

    /**
     * Test the property 'descrizione'
     */
    @Test
    public void descrizioneTest() {
        // TODO: test descrizione
    }

    /**
     * Test the property 'annotazioniMittente'
     */
    @Test
    public void annotazioniMittenteTest() {
        // TODO: test annotazioniMittente
    }

    /**
     * Test the property 'stampaAzienda'
     */
    @Test
    public void stampaAziendaTest() {
        // TODO: test stampaAzienda
    }

}
