/*
 * API Sprint - Documentazione
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import it.ibswebco.spint.JSON;

/**
 * V2modelliUpdateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T09:21:23.762486700+02:00[Europe/Rome]", comments = "Generator version: 7.21.0")
public class V2modelliUpdateRequest {
  public static final String SERIALIZED_NAME_DESCRIZIONE = "descrizione";
  @SerializedName(SERIALIZED_NAME_DESCRIZIONE)
  @javax.annotation.Nonnull
  private String descrizione;

  public static final String SERIALIZED_NAME_SPEDITORE = "speditore";
  @SerializedName(SERIALIZED_NAME_SPEDITORE)
  @javax.annotation.Nullable
  private String speditore;

  public static final String SERIALIZED_NAME_DESTINATARIO = "destinatario";
  @SerializedName(SERIALIZED_NAME_DESTINATARIO)
  @javax.annotation.Nullable
  private String destinatario;

  public static final String SERIALIZED_NAME_TRASPORTO = "trasporto";
  @SerializedName(SERIALIZED_NAME_TRASPORTO)
  @javax.annotation.Nullable
  private String trasporto;

  public static final String SERIALIZED_NAME_OSSERVAZIONI = "osservazioni";
  @SerializedName(SERIALIZED_NAME_OSSERVAZIONI)
  @javax.annotation.Nullable
  private String osservazioni;

  public static final String SERIALIZED_NAME_PAESE_DESTINAZIONE = "paese_destinazione";
  @SerializedName(SERIALIZED_NAME_PAESE_DESTINAZIONE)
  @javax.annotation.Nullable
  private String paeseDestinazione;

  public static final String SERIALIZED_NAME_AZIENDA_PRODUTTRICE = "azienda_produttrice";
  @SerializedName(SERIALIZED_NAME_AZIENDA_PRODUTTRICE)
  @javax.annotation.Nullable
  private String aziendaProduttrice;

  public static final String SERIALIZED_NAME_AZIENDA_MODIFICHE = "azienda_modifiche";
  @SerializedName(SERIALIZED_NAME_AZIENDA_MODIFICHE)
  @javax.annotation.Nullable
  private String aziendaModifiche;

  public static final String SERIALIZED_NAME_DOCUMENTAZIONE_ALLEGATA = "documentazione_allegata";
  @SerializedName(SERIALIZED_NAME_DOCUMENTAZIONE_ALLEGATA)
  @javax.annotation.Nullable
  private String documentazioneAllegata;

  public static final String SERIALIZED_NAME_GIACENZA_MERCI = "giacenza_merci";
  @SerializedName(SERIALIZED_NAME_GIACENZA_MERCI)
  @javax.annotation.Nullable
  private String giacenzaMerci;

  public static final String SERIALIZED_NAME_NCOPIE = "ncopie";
  @SerializedName(SERIALIZED_NAME_NCOPIE)
  @javax.annotation.Nullable
  private String ncopie = "0";

  public static final String SERIALIZED_NAME_NVISTI = "nvisti";
  @SerializedName(SERIALIZED_NAME_NVISTI)
  @javax.annotation.Nullable
  private String nvisti = "0";

  public static final String SERIALIZED_NAME_NLEG = "nleg";
  @SerializedName(SERIALIZED_NAME_NLEG)
  @javax.annotation.Nullable
  private String nleg = "0";

  public static final String SERIALIZED_NAME_FATT_FIRMATA = "fatt_firmata";
  @SerializedName(SERIALIZED_NAME_FATT_FIRMATA)
  @javax.annotation.Nullable
  private String fattFirmata = "S";

  public static final String SERIALIZED_NAME_NOTECCIAA = "notecciaa";
  @SerializedName(SERIALIZED_NAME_NOTECCIAA)
  @javax.annotation.Nullable
  private String notecciaa = "";

  public V2modelliUpdateRequest() {
  }

  public V2modelliUpdateRequest descrizione(@javax.annotation.Nonnull String descrizione) {
    this.descrizione = descrizione;
    return this;
  }

  /**
   * Get descrizione
   * @return descrizione
   */
  @javax.annotation.Nonnull
  public String getDescrizione() {
    return descrizione;
  }

  public void setDescrizione(@javax.annotation.Nonnull String descrizione) {
    this.descrizione = descrizione;
  }


  public V2modelliUpdateRequest speditore(@javax.annotation.Nullable String speditore) {
    this.speditore = speditore;
    return this;
  }

  /**
   * Get speditore
   * @return speditore
   */
  @javax.annotation.Nullable
  public String getSpeditore() {
    return speditore;
  }

  public void setSpeditore(@javax.annotation.Nullable String speditore) {
    this.speditore = speditore;
  }


  public V2modelliUpdateRequest destinatario(@javax.annotation.Nullable String destinatario) {
    this.destinatario = destinatario;
    return this;
  }

  /**
   * Get destinatario
   * @return destinatario
   */
  @javax.annotation.Nullable
  public String getDestinatario() {
    return destinatario;
  }

  public void setDestinatario(@javax.annotation.Nullable String destinatario) {
    this.destinatario = destinatario;
  }


  public V2modelliUpdateRequest trasporto(@javax.annotation.Nullable String trasporto) {
    this.trasporto = trasporto;
    return this;
  }

  /**
   * &#39;paese_origine&#39; &#x3D;&gt; &#39;max:256&#39;,
   * @return trasporto
   */
  @javax.annotation.Nullable
  public String getTrasporto() {
    return trasporto;
  }

  public void setTrasporto(@javax.annotation.Nullable String trasporto) {
    this.trasporto = trasporto;
  }


  public V2modelliUpdateRequest osservazioni(@javax.annotation.Nullable String osservazioni) {
    this.osservazioni = osservazioni;
    return this;
  }

  /**
   * Get osservazioni
   * @return osservazioni
   */
  @javax.annotation.Nullable
  public String getOsservazioni() {
    return osservazioni;
  }

  public void setOsservazioni(@javax.annotation.Nullable String osservazioni) {
    this.osservazioni = osservazioni;
  }


  public V2modelliUpdateRequest paeseDestinazione(@javax.annotation.Nullable String paeseDestinazione) {
    this.paeseDestinazione = paeseDestinazione;
    return this;
  }

  /**
   * &#39;merci&#39; &#x3D;&gt; &#39;max:3500&#39;, &#39;quantita&#39; &#x3D;&gt; &#39;max:3500&#39;,
   * @return paeseDestinazione
   */
  @javax.annotation.Nullable
  public String getPaeseDestinazione() {
    return paeseDestinazione;
  }

  public void setPaeseDestinazione(@javax.annotation.Nullable String paeseDestinazione) {
    this.paeseDestinazione = paeseDestinazione;
  }


  public V2modelliUpdateRequest aziendaProduttrice(@javax.annotation.Nullable String aziendaProduttrice) {
    this.aziendaProduttrice = aziendaProduttrice;
    return this;
  }

  /**
   * Get aziendaProduttrice
   * @return aziendaProduttrice
   */
  @javax.annotation.Nullable
  public String getAziendaProduttrice() {
    return aziendaProduttrice;
  }

  public void setAziendaProduttrice(@javax.annotation.Nullable String aziendaProduttrice) {
    this.aziendaProduttrice = aziendaProduttrice;
  }


  public V2modelliUpdateRequest aziendaModifiche(@javax.annotation.Nullable String aziendaModifiche) {
    this.aziendaModifiche = aziendaModifiche;
    return this;
  }

  /**
   * Get aziendaModifiche
   * @return aziendaModifiche
   */
  @javax.annotation.Nullable
  public String getAziendaModifiche() {
    return aziendaModifiche;
  }

  public void setAziendaModifiche(@javax.annotation.Nullable String aziendaModifiche) {
    this.aziendaModifiche = aziendaModifiche;
  }


  public V2modelliUpdateRequest documentazioneAllegata(@javax.annotation.Nullable String documentazioneAllegata) {
    this.documentazioneAllegata = documentazioneAllegata;
    return this;
  }

  /**
   * Get documentazioneAllegata
   * @return documentazioneAllegata
   */
  @javax.annotation.Nullable
  public String getDocumentazioneAllegata() {
    return documentazioneAllegata;
  }

  public void setDocumentazioneAllegata(@javax.annotation.Nullable String documentazioneAllegata) {
    this.documentazioneAllegata = documentazioneAllegata;
  }


  public V2modelliUpdateRequest giacenzaMerci(@javax.annotation.Nullable String giacenzaMerci) {
    this.giacenzaMerci = giacenzaMerci;
    return this;
  }

  /**
   * Get giacenzaMerci
   * @return giacenzaMerci
   */
  @javax.annotation.Nullable
  public String getGiacenzaMerci() {
    return giacenzaMerci;
  }

  public void setGiacenzaMerci(@javax.annotation.Nullable String giacenzaMerci) {
    this.giacenzaMerci = giacenzaMerci;
  }


  public V2modelliUpdateRequest ncopie(@javax.annotation.Nullable String ncopie) {
    this.ncopie = ncopie;
    return this;
  }

  /**
   * Get ncopie
   * @return ncopie
   */
  @javax.annotation.Nullable
  public String getNcopie() {
    return ncopie;
  }

  public void setNcopie(@javax.annotation.Nullable String ncopie) {
    this.ncopie = ncopie;
  }


  public V2modelliUpdateRequest nvisti(@javax.annotation.Nullable String nvisti) {
    this.nvisti = nvisti;
    return this;
  }

  /**
   * Get nvisti
   * @return nvisti
   */
  @javax.annotation.Nullable
  public String getNvisti() {
    return nvisti;
  }

  public void setNvisti(@javax.annotation.Nullable String nvisti) {
    this.nvisti = nvisti;
  }


  public V2modelliUpdateRequest nleg(@javax.annotation.Nullable String nleg) {
    this.nleg = nleg;
    return this;
  }

  /**
   * Get nleg
   * @return nleg
   */
  @javax.annotation.Nullable
  public String getNleg() {
    return nleg;
  }

  public void setNleg(@javax.annotation.Nullable String nleg) {
    this.nleg = nleg;
  }


  public V2modelliUpdateRequest fattFirmata(@javax.annotation.Nullable String fattFirmata) {
    this.fattFirmata = fattFirmata;
    return this;
  }

  /**
   * Get fattFirmata
   * @return fattFirmata
   */
  @javax.annotation.Nullable
  public String getFattFirmata() {
    return fattFirmata;
  }

  public void setFattFirmata(@javax.annotation.Nullable String fattFirmata) {
    this.fattFirmata = fattFirmata;
  }


  public V2modelliUpdateRequest notecciaa(@javax.annotation.Nullable String notecciaa) {
    this.notecciaa = notecciaa;
    return this;
  }

  /**
   * Get notecciaa
   * @return notecciaa
   */
  @javax.annotation.Nullable
  public String getNotecciaa() {
    return notecciaa;
  }

  public void setNotecciaa(@javax.annotation.Nullable String notecciaa) {
    this.notecciaa = notecciaa;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the V2modelliUpdateRequest instance itself
   */
  public V2modelliUpdateRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2modelliUpdateRequest v2modelliUpdateRequest = (V2modelliUpdateRequest) o;
    return Objects.equals(this.descrizione, v2modelliUpdateRequest.descrizione) &&
        Objects.equals(this.speditore, v2modelliUpdateRequest.speditore) &&
        Objects.equals(this.destinatario, v2modelliUpdateRequest.destinatario) &&
        Objects.equals(this.trasporto, v2modelliUpdateRequest.trasporto) &&
        Objects.equals(this.osservazioni, v2modelliUpdateRequest.osservazioni) &&
        Objects.equals(this.paeseDestinazione, v2modelliUpdateRequest.paeseDestinazione) &&
        Objects.equals(this.aziendaProduttrice, v2modelliUpdateRequest.aziendaProduttrice) &&
        Objects.equals(this.aziendaModifiche, v2modelliUpdateRequest.aziendaModifiche) &&
        Objects.equals(this.documentazioneAllegata, v2modelliUpdateRequest.documentazioneAllegata) &&
        Objects.equals(this.giacenzaMerci, v2modelliUpdateRequest.giacenzaMerci) &&
        Objects.equals(this.ncopie, v2modelliUpdateRequest.ncopie) &&
        Objects.equals(this.nvisti, v2modelliUpdateRequest.nvisti) &&
        Objects.equals(this.nleg, v2modelliUpdateRequest.nleg) &&
        Objects.equals(this.fattFirmata, v2modelliUpdateRequest.fattFirmata) &&
        Objects.equals(this.notecciaa, v2modelliUpdateRequest.notecciaa)&&
        Objects.equals(this.additionalProperties, v2modelliUpdateRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(descrizione, speditore, destinatario, trasporto, osservazioni, paeseDestinazione, aziendaProduttrice, aziendaModifiche, documentazioneAllegata, giacenzaMerci, ncopie, nvisti, nleg, fattFirmata, notecciaa, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2modelliUpdateRequest {\n");
    sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
    sb.append("    speditore: ").append(toIndentedString(speditore)).append("\n");
    sb.append("    destinatario: ").append(toIndentedString(destinatario)).append("\n");
    sb.append("    trasporto: ").append(toIndentedString(trasporto)).append("\n");
    sb.append("    osservazioni: ").append(toIndentedString(osservazioni)).append("\n");
    sb.append("    paeseDestinazione: ").append(toIndentedString(paeseDestinazione)).append("\n");
    sb.append("    aziendaProduttrice: ").append(toIndentedString(aziendaProduttrice)).append("\n");
    sb.append("    aziendaModifiche: ").append(toIndentedString(aziendaModifiche)).append("\n");
    sb.append("    documentazioneAllegata: ").append(toIndentedString(documentazioneAllegata)).append("\n");
    sb.append("    giacenzaMerci: ").append(toIndentedString(giacenzaMerci)).append("\n");
    sb.append("    ncopie: ").append(toIndentedString(ncopie)).append("\n");
    sb.append("    nvisti: ").append(toIndentedString(nvisti)).append("\n");
    sb.append("    nleg: ").append(toIndentedString(nleg)).append("\n");
    sb.append("    fattFirmata: ").append(toIndentedString(fattFirmata)).append("\n");
    sb.append("    notecciaa: ").append(toIndentedString(notecciaa)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("descrizione", "speditore", "destinatario", "trasporto", "osservazioni", "paese_destinazione", "azienda_produttrice", "azienda_modifiche", "documentazione_allegata", "giacenza_merci", "ncopie", "nvisti", "nleg", "fatt_firmata", "notecciaa"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("descrizione"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to V2modelliUpdateRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V2modelliUpdateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in V2modelliUpdateRequest is not found in the empty JSON string", V2modelliUpdateRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V2modelliUpdateRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("descrizione").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `descrizione` to be a primitive type in the JSON string but got `%s`", jsonObj.get("descrizione").toString()));
      }
      if ((jsonObj.get("speditore") != null && !jsonObj.get("speditore").isJsonNull()) && !jsonObj.get("speditore").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `speditore` to be a primitive type in the JSON string but got `%s`", jsonObj.get("speditore").toString()));
      }
      if ((jsonObj.get("destinatario") != null && !jsonObj.get("destinatario").isJsonNull()) && !jsonObj.get("destinatario").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `destinatario` to be a primitive type in the JSON string but got `%s`", jsonObj.get("destinatario").toString()));
      }
      if ((jsonObj.get("trasporto") != null && !jsonObj.get("trasporto").isJsonNull()) && !jsonObj.get("trasporto").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `trasporto` to be a primitive type in the JSON string but got `%s`", jsonObj.get("trasporto").toString()));
      }
      if ((jsonObj.get("osservazioni") != null && !jsonObj.get("osservazioni").isJsonNull()) && !jsonObj.get("osservazioni").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `osservazioni` to be a primitive type in the JSON string but got `%s`", jsonObj.get("osservazioni").toString()));
      }
      if ((jsonObj.get("paese_destinazione") != null && !jsonObj.get("paese_destinazione").isJsonNull()) && !jsonObj.get("paese_destinazione").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `paese_destinazione` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paese_destinazione").toString()));
      }
      if ((jsonObj.get("azienda_produttrice") != null && !jsonObj.get("azienda_produttrice").isJsonNull()) && !jsonObj.get("azienda_produttrice").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `azienda_produttrice` to be a primitive type in the JSON string but got `%s`", jsonObj.get("azienda_produttrice").toString()));
      }
      if ((jsonObj.get("azienda_modifiche") != null && !jsonObj.get("azienda_modifiche").isJsonNull()) && !jsonObj.get("azienda_modifiche").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `azienda_modifiche` to be a primitive type in the JSON string but got `%s`", jsonObj.get("azienda_modifiche").toString()));
      }
      if ((jsonObj.get("documentazione_allegata") != null && !jsonObj.get("documentazione_allegata").isJsonNull()) && !jsonObj.get("documentazione_allegata").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `documentazione_allegata` to be a primitive type in the JSON string but got `%s`", jsonObj.get("documentazione_allegata").toString()));
      }
      if ((jsonObj.get("giacenza_merci") != null && !jsonObj.get("giacenza_merci").isJsonNull()) && !jsonObj.get("giacenza_merci").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `giacenza_merci` to be a primitive type in the JSON string but got `%s`", jsonObj.get("giacenza_merci").toString()));
      }
      if ((jsonObj.get("ncopie") != null && !jsonObj.get("ncopie").isJsonNull()) && !jsonObj.get("ncopie").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ncopie` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ncopie").toString()));
      }
      if ((jsonObj.get("nvisti") != null && !jsonObj.get("nvisti").isJsonNull()) && !jsonObj.get("nvisti").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `nvisti` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nvisti").toString()));
      }
      if ((jsonObj.get("nleg") != null && !jsonObj.get("nleg").isJsonNull()) && !jsonObj.get("nleg").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `nleg` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nleg").toString()));
      }
      if ((jsonObj.get("fatt_firmata") != null && !jsonObj.get("fatt_firmata").isJsonNull()) && !jsonObj.get("fatt_firmata").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `fatt_firmata` to be a primitive type in the JSON string but got `%s`", jsonObj.get("fatt_firmata").toString()));
      }
      if ((jsonObj.get("notecciaa") != null && !jsonObj.get("notecciaa").isJsonNull()) && !jsonObj.get("notecciaa").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `notecciaa` to be a primitive type in the JSON string but got `%s`", jsonObj.get("notecciaa").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V2modelliUpdateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V2modelliUpdateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V2modelliUpdateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V2modelliUpdateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<V2modelliUpdateRequest>() {
           @Override
           public void write(JsonWriter out, V2modelliUpdateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public V2modelliUpdateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             V2modelliUpdateRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of V2modelliUpdateRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of V2modelliUpdateRequest
   * @throws IOException if the JSON string is invalid with respect to V2modelliUpdateRequest
   */
  public static V2modelliUpdateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V2modelliUpdateRequest.class);
  }

  /**
   * Convert an instance of V2modelliUpdateRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

