/*
 * API Sprint - Documentazione
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.V2richiesteStoreRequestCciaa;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import it.ibswebco.spint.JSON;

/**
 * V2richiesteUpdateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T09:21:23.762486700+02:00[Europe/Rome]", comments = "Generator version: 7.21.0")
public class V2richiesteUpdateRequest {
  public static final String SERIALIZED_NAME_DESCRIZIONE = "descrizione";
  @SerializedName(SERIALIZED_NAME_DESCRIZIONE)
  @javax.annotation.Nonnull
  private String descrizione;

  public static final String SERIALIZED_NAME_SPEDITORE = "speditore";
  @SerializedName(SERIALIZED_NAME_SPEDITORE)
  @javax.annotation.Nonnull
  private String speditore;

  public static final String SERIALIZED_NAME_DESTINATARIO = "destinatario";
  @SerializedName(SERIALIZED_NAME_DESTINATARIO)
  @javax.annotation.Nonnull
  private String destinatario;

  public static final String SERIALIZED_NAME_PAESE_ORIGINE = "paese_origine";
  @SerializedName(SERIALIZED_NAME_PAESE_ORIGINE)
  @javax.annotation.Nonnull
  private String paeseOrigine;

  public static final String SERIALIZED_NAME_INFORMAZIONI = "informazioni";
  @SerializedName(SERIALIZED_NAME_INFORMAZIONI)
  @javax.annotation.Nullable
  private String informazioni;

  public static final String SERIALIZED_NAME_OSSERVAZIONI = "osservazioni";
  @SerializedName(SERIALIZED_NAME_OSSERVAZIONI)
  @javax.annotation.Nullable
  private String osservazioni;

  public static final String SERIALIZED_NAME_PAESE_DEST = "paese_dest";
  @SerializedName(SERIALIZED_NAME_PAESE_DEST)
  @javax.annotation.Nullable
  private String paeseDest;

  public static final String SERIALIZED_NAME_NUMERO_COPIE = "numero_copie";
  @SerializedName(SERIALIZED_NAME_NUMERO_COPIE)
  @javax.annotation.Nullable
  private String numeroCopie = "0";

  public static final String SERIALIZED_NAME_TRASPORTO = "trasporto";
  @SerializedName(SERIALIZED_NAME_TRASPORTO)
  @javax.annotation.Nullable
  private String trasporto;

  public static final String SERIALIZED_NAME_MERCI = "merci";
  @SerializedName(SERIALIZED_NAME_MERCI)
  @javax.annotation.Nullable
  private String merci;

  public static final String SERIALIZED_NAME_QUANTITA = "quantita";
  @SerializedName(SERIALIZED_NAME_QUANTITA)
  @javax.annotation.Nullable
  private String quantita;

  public static final String SERIALIZED_NAME_VALORE_MERCE = "valore_merce";
  @SerializedName(SERIALIZED_NAME_VALORE_MERCE)
  @javax.annotation.Nullable
  private String valoreMerce;

  public static final String SERIALIZED_NAME_NUMERO_AUT = "numero_aut";
  @SerializedName(SERIALIZED_NAME_NUMERO_AUT)
  @javax.annotation.Nullable
  private String numeroAut;

  public static final String SERIALIZED_NAME_PAESE_COMUNITARIO = "paese_comunitario";
  @SerializedName(SERIALIZED_NAME_PAESE_COMUNITARIO)
  @javax.annotation.Nullable
  private String paeseComunitario;

  public static final String SERIALIZED_NAME_PRODUZIONE = "produzione";
  @SerializedName(SERIALIZED_NAME_PRODUZIONE)
  @javax.annotation.Nullable
  private String produzione;

  public static final String SERIALIZED_NAME_AZIENDA_PRODUTTRICE = "azienda_produttrice";
  @SerializedName(SERIALIZED_NAME_AZIENDA_PRODUTTRICE)
  @javax.annotation.Nullable
  private String aziendaProduttrice;

  public static final String SERIALIZED_NAME_MODIFICHE = "modifiche";
  @SerializedName(SERIALIZED_NAME_MODIFICHE)
  @javax.annotation.Nullable
  private String modifiche;

  public static final String SERIALIZED_NAME_AZIENDA_MODIFICHE = "azienda_modifiche";
  @SerializedName(SERIALIZED_NAME_AZIENDA_MODIFICHE)
  @javax.annotation.Nullable
  private String aziendaModifiche;

  public static final String SERIALIZED_NAME_PAESE_EXTRAUE = "paese_extraue";
  @SerializedName(SERIALIZED_NAME_PAESE_EXTRAUE)
  @javax.annotation.Nullable
  private String paeseExtraue;

  public static final String SERIALIZED_NAME_DOCUMENTAZIONE_ALLEGATA = "documentazione_allegata";
  @SerializedName(SERIALIZED_NAME_DOCUMENTAZIONE_ALLEGATA)
  @javax.annotation.Nullable
  private String documentazioneAllegata;

  public static final String SERIALIZED_NAME_GIACENZA_MERCI = "giacenza_merci";
  @SerializedName(SERIALIZED_NAME_GIACENZA_MERCI)
  @javax.annotation.Nullable
  private String giacenzaMerci;

  public static final String SERIALIZED_NAME_ANNOTAZIONI_MITTENTE = "annotazioni_mittente";
  @SerializedName(SERIALIZED_NAME_ANNOTAZIONI_MITTENTE)
  @javax.annotation.Nullable
  private String annotazioniMittente;

  public static final String SERIALIZED_NAME_ANNOTAZIONI_INTERNE = "annotazioni_interne";
  @SerializedName(SERIALIZED_NAME_ANNOTAZIONI_INTERNE)
  @javax.annotation.Nullable
  private String annotazioniInterne;

  public static final String SERIALIZED_NAME_PROFORMA = "proforma";
  @SerializedName(SERIALIZED_NAME_PROFORMA)
  @javax.annotation.Nullable
  private String proforma;

  public static final String SERIALIZED_NAME_URGENTE = "urgente";
  @SerializedName(SERIALIZED_NAME_URGENTE)
  @javax.annotation.Nullable
  private String urgente;

  public static final String SERIALIZED_NAME_EMAIL_CONTATTO = "email_contatto";
  @SerializedName(SERIALIZED_NAME_EMAIL_CONTATTO)
  @javax.annotation.Nullable
  private String emailContatto;

  public static final String SERIALIZED_NAME_CCIAA = "cciaa";
  @SerializedName(SERIALIZED_NAME_CCIAA)
  @javax.annotation.Nullable
  private V2richiesteStoreRequestCciaa cciaa;

  public V2richiesteUpdateRequest() {
  }

  public V2richiesteUpdateRequest descrizione(@javax.annotation.Nonnull String descrizione) {
    this.descrizione = descrizione;
    return this;
  }

  /**
   * Get descrizione
   * @return descrizione
   */
  @javax.annotation.Nonnull
  public String getDescrizione() {
    return descrizione;
  }

  public void setDescrizione(@javax.annotation.Nonnull String descrizione) {
    this.descrizione = descrizione;
  }


  public V2richiesteUpdateRequest speditore(@javax.annotation.Nonnull String speditore) {
    this.speditore = speditore;
    return this;
  }

  /**
   * Get speditore
   * @return speditore
   */
  @javax.annotation.Nonnull
  public String getSpeditore() {
    return speditore;
  }

  public void setSpeditore(@javax.annotation.Nonnull String speditore) {
    this.speditore = speditore;
  }


  public V2richiesteUpdateRequest destinatario(@javax.annotation.Nonnull String destinatario) {
    this.destinatario = destinatario;
    return this;
  }

  /**
   * Get destinatario
   * @return destinatario
   */
  @javax.annotation.Nonnull
  public String getDestinatario() {
    return destinatario;
  }

  public void setDestinatario(@javax.annotation.Nonnull String destinatario) {
    this.destinatario = destinatario;
  }


  public V2richiesteUpdateRequest paeseOrigine(@javax.annotation.Nonnull String paeseOrigine) {
    this.paeseOrigine = paeseOrigine;
    return this;
  }

  /**
   * Get paeseOrigine
   * @return paeseOrigine
   */
  @javax.annotation.Nonnull
  public String getPaeseOrigine() {
    return paeseOrigine;
  }

  public void setPaeseOrigine(@javax.annotation.Nonnull String paeseOrigine) {
    this.paeseOrigine = paeseOrigine;
  }


  public V2richiesteUpdateRequest informazioni(@javax.annotation.Nullable String informazioni) {
    this.informazioni = informazioni;
    return this;
  }

  /**
   * Get informazioni
   * @return informazioni
   */
  @javax.annotation.Nullable
  public String getInformazioni() {
    return informazioni;
  }

  public void setInformazioni(@javax.annotation.Nullable String informazioni) {
    this.informazioni = informazioni;
  }


  public V2richiesteUpdateRequest osservazioni(@javax.annotation.Nullable String osservazioni) {
    this.osservazioni = osservazioni;
    return this;
  }

  /**
   * Get osservazioni
   * @return osservazioni
   */
  @javax.annotation.Nullable
  public String getOsservazioni() {
    return osservazioni;
  }

  public void setOsservazioni(@javax.annotation.Nullable String osservazioni) {
    this.osservazioni = osservazioni;
  }


  public V2richiesteUpdateRequest paeseDest(@javax.annotation.Nullable String paeseDest) {
    this.paeseDest = paeseDest;
    return this;
  }

  /**
   * Get paeseDest
   * @return paeseDest
   */
  @javax.annotation.Nullable
  public String getPaeseDest() {
    return paeseDest;
  }

  public void setPaeseDest(@javax.annotation.Nullable String paeseDest) {
    this.paeseDest = paeseDest;
  }


  public V2richiesteUpdateRequest numeroCopie(@javax.annotation.Nullable String numeroCopie) {
    this.numeroCopie = numeroCopie;
    return this;
  }

  /**
   * Get numeroCopie
   * @return numeroCopie
   */
  @javax.annotation.Nullable
  public String getNumeroCopie() {
    return numeroCopie;
  }

  public void setNumeroCopie(@javax.annotation.Nullable String numeroCopie) {
    this.numeroCopie = numeroCopie;
  }


  public V2richiesteUpdateRequest trasporto(@javax.annotation.Nullable String trasporto) {
    this.trasporto = trasporto;
    return this;
  }

  /**
   * Get trasporto
   * @return trasporto
   */
  @javax.annotation.Nullable
  public String getTrasporto() {
    return trasporto;
  }

  public void setTrasporto(@javax.annotation.Nullable String trasporto) {
    this.trasporto = trasporto;
  }


  public V2richiesteUpdateRequest merci(@javax.annotation.Nullable String merci) {
    this.merci = merci;
    return this;
  }

  /**
   * Get merci
   * @return merci
   */
  @javax.annotation.Nullable
  public String getMerci() {
    return merci;
  }

  public void setMerci(@javax.annotation.Nullable String merci) {
    this.merci = merci;
  }


  public V2richiesteUpdateRequest quantita(@javax.annotation.Nullable String quantita) {
    this.quantita = quantita;
    return this;
  }

  /**
   * Get quantita
   * @return quantita
   */
  @javax.annotation.Nullable
  public String getQuantita() {
    return quantita;
  }

  public void setQuantita(@javax.annotation.Nullable String quantita) {
    this.quantita = quantita;
  }


  public V2richiesteUpdateRequest valoreMerce(@javax.annotation.Nullable String valoreMerce) {
    this.valoreMerce = valoreMerce;
    return this;
  }

  /**
   * Get valoreMerce
   * @return valoreMerce
   */
  @javax.annotation.Nullable
  public String getValoreMerce() {
    return valoreMerce;
  }

  public void setValoreMerce(@javax.annotation.Nullable String valoreMerce) {
    this.valoreMerce = valoreMerce;
  }


  public V2richiesteUpdateRequest numeroAut(@javax.annotation.Nullable String numeroAut) {
    this.numeroAut = numeroAut;
    return this;
  }

  /**
   * Get numeroAut
   * @return numeroAut
   */
  @javax.annotation.Nullable
  public String getNumeroAut() {
    return numeroAut;
  }

  public void setNumeroAut(@javax.annotation.Nullable String numeroAut) {
    this.numeroAut = numeroAut;
  }


  public V2richiesteUpdateRequest paeseComunitario(@javax.annotation.Nullable String paeseComunitario) {
    this.paeseComunitario = paeseComunitario;
    return this;
  }

  /**
   * Get paeseComunitario
   * @return paeseComunitario
   */
  @javax.annotation.Nullable
  public String getPaeseComunitario() {
    return paeseComunitario;
  }

  public void setPaeseComunitario(@javax.annotation.Nullable String paeseComunitario) {
    this.paeseComunitario = paeseComunitario;
  }


  public V2richiesteUpdateRequest produzione(@javax.annotation.Nullable String produzione) {
    this.produzione = produzione;
    return this;
  }

  /**
   * Get produzione
   * @return produzione
   */
  @javax.annotation.Nullable
  public String getProduzione() {
    return produzione;
  }

  public void setProduzione(@javax.annotation.Nullable String produzione) {
    this.produzione = produzione;
  }


  public V2richiesteUpdateRequest aziendaProduttrice(@javax.annotation.Nullable String aziendaProduttrice) {
    this.aziendaProduttrice = aziendaProduttrice;
    return this;
  }

  /**
   * Get aziendaProduttrice
   * @return aziendaProduttrice
   */
  @javax.annotation.Nullable
  public String getAziendaProduttrice() {
    return aziendaProduttrice;
  }

  public void setAziendaProduttrice(@javax.annotation.Nullable String aziendaProduttrice) {
    this.aziendaProduttrice = aziendaProduttrice;
  }


  public V2richiesteUpdateRequest modifiche(@javax.annotation.Nullable String modifiche) {
    this.modifiche = modifiche;
    return this;
  }

  /**
   * Get modifiche
   * @return modifiche
   */
  @javax.annotation.Nullable
  public String getModifiche() {
    return modifiche;
  }

  public void setModifiche(@javax.annotation.Nullable String modifiche) {
    this.modifiche = modifiche;
  }


  public V2richiesteUpdateRequest aziendaModifiche(@javax.annotation.Nullable String aziendaModifiche) {
    this.aziendaModifiche = aziendaModifiche;
    return this;
  }

  /**
   * Get aziendaModifiche
   * @return aziendaModifiche
   */
  @javax.annotation.Nullable
  public String getAziendaModifiche() {
    return aziendaModifiche;
  }

  public void setAziendaModifiche(@javax.annotation.Nullable String aziendaModifiche) {
    this.aziendaModifiche = aziendaModifiche;
  }


  public V2richiesteUpdateRequest paeseExtraue(@javax.annotation.Nullable String paeseExtraue) {
    this.paeseExtraue = paeseExtraue;
    return this;
  }

  /**
   * Get paeseExtraue
   * @return paeseExtraue
   */
  @javax.annotation.Nullable
  public String getPaeseExtraue() {
    return paeseExtraue;
  }

  public void setPaeseExtraue(@javax.annotation.Nullable String paeseExtraue) {
    this.paeseExtraue = paeseExtraue;
  }


  public V2richiesteUpdateRequest documentazioneAllegata(@javax.annotation.Nullable String documentazioneAllegata) {
    this.documentazioneAllegata = documentazioneAllegata;
    return this;
  }

  /**
   * Get documentazioneAllegata
   * @return documentazioneAllegata
   */
  @javax.annotation.Nullable
  public String getDocumentazioneAllegata() {
    return documentazioneAllegata;
  }

  public void setDocumentazioneAllegata(@javax.annotation.Nullable String documentazioneAllegata) {
    this.documentazioneAllegata = documentazioneAllegata;
  }


  public V2richiesteUpdateRequest giacenzaMerci(@javax.annotation.Nullable String giacenzaMerci) {
    this.giacenzaMerci = giacenzaMerci;
    return this;
  }

  /**
   * Get giacenzaMerci
   * @return giacenzaMerci
   */
  @javax.annotation.Nullable
  public String getGiacenzaMerci() {
    return giacenzaMerci;
  }

  public void setGiacenzaMerci(@javax.annotation.Nullable String giacenzaMerci) {
    this.giacenzaMerci = giacenzaMerci;
  }


  public V2richiesteUpdateRequest annotazioniMittente(@javax.annotation.Nullable String annotazioniMittente) {
    this.annotazioniMittente = annotazioniMittente;
    return this;
  }

  /**
   * Get annotazioniMittente
   * @return annotazioniMittente
   */
  @javax.annotation.Nullable
  public String getAnnotazioniMittente() {
    return annotazioniMittente;
  }

  public void setAnnotazioniMittente(@javax.annotation.Nullable String annotazioniMittente) {
    this.annotazioniMittente = annotazioniMittente;
  }


  public V2richiesteUpdateRequest annotazioniInterne(@javax.annotation.Nullable String annotazioniInterne) {
    this.annotazioniInterne = annotazioniInterne;
    return this;
  }

  /**
   * Get annotazioniInterne
   * @return annotazioniInterne
   */
  @javax.annotation.Nullable
  public String getAnnotazioniInterne() {
    return annotazioniInterne;
  }

  public void setAnnotazioniInterne(@javax.annotation.Nullable String annotazioniInterne) {
    this.annotazioniInterne = annotazioniInterne;
  }


  public V2richiesteUpdateRequest proforma(@javax.annotation.Nullable String proforma) {
    this.proforma = proforma;
    return this;
  }

  /**
   * Get proforma
   * @return proforma
   */
  @javax.annotation.Nullable
  public String getProforma() {
    return proforma;
  }

  public void setProforma(@javax.annotation.Nullable String proforma) {
    this.proforma = proforma;
  }


  public V2richiesteUpdateRequest urgente(@javax.annotation.Nullable String urgente) {
    this.urgente = urgente;
    return this;
  }

  /**
   * Get urgente
   * @return urgente
   */
  @javax.annotation.Nullable
  public String getUrgente() {
    return urgente;
  }

  public void setUrgente(@javax.annotation.Nullable String urgente) {
    this.urgente = urgente;
  }


  public V2richiesteUpdateRequest emailContatto(@javax.annotation.Nullable String emailContatto) {
    this.emailContatto = emailContatto;
    return this;
  }

  /**
   * Get emailContatto
   * @return emailContatto
   */
  @javax.annotation.Nullable
  public String getEmailContatto() {
    return emailContatto;
  }

  public void setEmailContatto(@javax.annotation.Nullable String emailContatto) {
    this.emailContatto = emailContatto;
  }


  public V2richiesteUpdateRequest cciaa(@javax.annotation.Nullable V2richiesteStoreRequestCciaa cciaa) {
    this.cciaa = cciaa;
    return this;
  }

  /**
   * Get cciaa
   * @return cciaa
   */
  @javax.annotation.Nullable
  public V2richiesteStoreRequestCciaa getCciaa() {
    return cciaa;
  }

  public void setCciaa(@javax.annotation.Nullable V2richiesteStoreRequestCciaa cciaa) {
    this.cciaa = cciaa;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the V2richiesteUpdateRequest instance itself
   */
  public V2richiesteUpdateRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2richiesteUpdateRequest v2richiesteUpdateRequest = (V2richiesteUpdateRequest) o;
    return Objects.equals(this.descrizione, v2richiesteUpdateRequest.descrizione) &&
        Objects.equals(this.speditore, v2richiesteUpdateRequest.speditore) &&
        Objects.equals(this.destinatario, v2richiesteUpdateRequest.destinatario) &&
        Objects.equals(this.paeseOrigine, v2richiesteUpdateRequest.paeseOrigine) &&
        Objects.equals(this.informazioni, v2richiesteUpdateRequest.informazioni) &&
        Objects.equals(this.osservazioni, v2richiesteUpdateRequest.osservazioni) &&
        Objects.equals(this.paeseDest, v2richiesteUpdateRequest.paeseDest) &&
        Objects.equals(this.numeroCopie, v2richiesteUpdateRequest.numeroCopie) &&
        Objects.equals(this.trasporto, v2richiesteUpdateRequest.trasporto) &&
        Objects.equals(this.merci, v2richiesteUpdateRequest.merci) &&
        Objects.equals(this.quantita, v2richiesteUpdateRequest.quantita) &&
        Objects.equals(this.valoreMerce, v2richiesteUpdateRequest.valoreMerce) &&
        Objects.equals(this.numeroAut, v2richiesteUpdateRequest.numeroAut) &&
        Objects.equals(this.paeseComunitario, v2richiesteUpdateRequest.paeseComunitario) &&
        Objects.equals(this.produzione, v2richiesteUpdateRequest.produzione) &&
        Objects.equals(this.aziendaProduttrice, v2richiesteUpdateRequest.aziendaProduttrice) &&
        Objects.equals(this.modifiche, v2richiesteUpdateRequest.modifiche) &&
        Objects.equals(this.aziendaModifiche, v2richiesteUpdateRequest.aziendaModifiche) &&
        Objects.equals(this.paeseExtraue, v2richiesteUpdateRequest.paeseExtraue) &&
        Objects.equals(this.documentazioneAllegata, v2richiesteUpdateRequest.documentazioneAllegata) &&
        Objects.equals(this.giacenzaMerci, v2richiesteUpdateRequest.giacenzaMerci) &&
        Objects.equals(this.annotazioniMittente, v2richiesteUpdateRequest.annotazioniMittente) &&
        Objects.equals(this.annotazioniInterne, v2richiesteUpdateRequest.annotazioniInterne) &&
        Objects.equals(this.proforma, v2richiesteUpdateRequest.proforma) &&
        Objects.equals(this.urgente, v2richiesteUpdateRequest.urgente) &&
        Objects.equals(this.emailContatto, v2richiesteUpdateRequest.emailContatto) &&
        Objects.equals(this.cciaa, v2richiesteUpdateRequest.cciaa)&&
        Objects.equals(this.additionalProperties, v2richiesteUpdateRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(descrizione, speditore, destinatario, paeseOrigine, informazioni, osservazioni, paeseDest, numeroCopie, trasporto, merci, quantita, valoreMerce, numeroAut, paeseComunitario, produzione, aziendaProduttrice, modifiche, aziendaModifiche, paeseExtraue, documentazioneAllegata, giacenzaMerci, annotazioniMittente, annotazioniInterne, proforma, urgente, emailContatto, cciaa, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2richiesteUpdateRequest {\n");
    sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
    sb.append("    speditore: ").append(toIndentedString(speditore)).append("\n");
    sb.append("    destinatario: ").append(toIndentedString(destinatario)).append("\n");
    sb.append("    paeseOrigine: ").append(toIndentedString(paeseOrigine)).append("\n");
    sb.append("    informazioni: ").append(toIndentedString(informazioni)).append("\n");
    sb.append("    osservazioni: ").append(toIndentedString(osservazioni)).append("\n");
    sb.append("    paeseDest: ").append(toIndentedString(paeseDest)).append("\n");
    sb.append("    numeroCopie: ").append(toIndentedString(numeroCopie)).append("\n");
    sb.append("    trasporto: ").append(toIndentedString(trasporto)).append("\n");
    sb.append("    merci: ").append(toIndentedString(merci)).append("\n");
    sb.append("    quantita: ").append(toIndentedString(quantita)).append("\n");
    sb.append("    valoreMerce: ").append(toIndentedString(valoreMerce)).append("\n");
    sb.append("    numeroAut: ").append(toIndentedString(numeroAut)).append("\n");
    sb.append("    paeseComunitario: ").append(toIndentedString(paeseComunitario)).append("\n");
    sb.append("    produzione: ").append(toIndentedString(produzione)).append("\n");
    sb.append("    aziendaProduttrice: ").append(toIndentedString(aziendaProduttrice)).append("\n");
    sb.append("    modifiche: ").append(toIndentedString(modifiche)).append("\n");
    sb.append("    aziendaModifiche: ").append(toIndentedString(aziendaModifiche)).append("\n");
    sb.append("    paeseExtraue: ").append(toIndentedString(paeseExtraue)).append("\n");
    sb.append("    documentazioneAllegata: ").append(toIndentedString(documentazioneAllegata)).append("\n");
    sb.append("    giacenzaMerci: ").append(toIndentedString(giacenzaMerci)).append("\n");
    sb.append("    annotazioniMittente: ").append(toIndentedString(annotazioniMittente)).append("\n");
    sb.append("    annotazioniInterne: ").append(toIndentedString(annotazioniInterne)).append("\n");
    sb.append("    proforma: ").append(toIndentedString(proforma)).append("\n");
    sb.append("    urgente: ").append(toIndentedString(urgente)).append("\n");
    sb.append("    emailContatto: ").append(toIndentedString(emailContatto)).append("\n");
    sb.append("    cciaa: ").append(toIndentedString(cciaa)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("descrizione", "speditore", "destinatario", "paese_origine", "informazioni", "osservazioni", "paese_dest", "numero_copie", "trasporto", "merci", "quantita", "valore_merce", "numero_aut", "paese_comunitario", "produzione", "azienda_produttrice", "modifiche", "azienda_modifiche", "paese_extraue", "documentazione_allegata", "giacenza_merci", "annotazioni_mittente", "annotazioni_interne", "proforma", "urgente", "email_contatto", "cciaa"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("descrizione", "speditore", "destinatario", "paese_origine"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to V2richiesteUpdateRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V2richiesteUpdateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in V2richiesteUpdateRequest is not found in the empty JSON string", V2richiesteUpdateRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V2richiesteUpdateRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("descrizione").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `descrizione` to be a primitive type in the JSON string but got `%s`", jsonObj.get("descrizione").toString()));
      }
      if (!jsonObj.get("speditore").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `speditore` to be a primitive type in the JSON string but got `%s`", jsonObj.get("speditore").toString()));
      }
      if (!jsonObj.get("destinatario").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `destinatario` to be a primitive type in the JSON string but got `%s`", jsonObj.get("destinatario").toString()));
      }
      if (!jsonObj.get("paese_origine").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `paese_origine` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paese_origine").toString()));
      }
      if ((jsonObj.get("informazioni") != null && !jsonObj.get("informazioni").isJsonNull()) && !jsonObj.get("informazioni").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `informazioni` to be a primitive type in the JSON string but got `%s`", jsonObj.get("informazioni").toString()));
      }
      if ((jsonObj.get("osservazioni") != null && !jsonObj.get("osservazioni").isJsonNull()) && !jsonObj.get("osservazioni").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `osservazioni` to be a primitive type in the JSON string but got `%s`", jsonObj.get("osservazioni").toString()));
      }
      if ((jsonObj.get("paese_dest") != null && !jsonObj.get("paese_dest").isJsonNull()) && !jsonObj.get("paese_dest").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `paese_dest` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paese_dest").toString()));
      }
      if ((jsonObj.get("numero_copie") != null && !jsonObj.get("numero_copie").isJsonNull()) && !jsonObj.get("numero_copie").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `numero_copie` to be a primitive type in the JSON string but got `%s`", jsonObj.get("numero_copie").toString()));
      }
      if ((jsonObj.get("trasporto") != null && !jsonObj.get("trasporto").isJsonNull()) && !jsonObj.get("trasporto").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `trasporto` to be a primitive type in the JSON string but got `%s`", jsonObj.get("trasporto").toString()));
      }
      if ((jsonObj.get("merci") != null && !jsonObj.get("merci").isJsonNull()) && !jsonObj.get("merci").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `merci` to be a primitive type in the JSON string but got `%s`", jsonObj.get("merci").toString()));
      }
      if ((jsonObj.get("quantita") != null && !jsonObj.get("quantita").isJsonNull()) && !jsonObj.get("quantita").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `quantita` to be a primitive type in the JSON string but got `%s`", jsonObj.get("quantita").toString()));
      }
      if ((jsonObj.get("valore_merce") != null && !jsonObj.get("valore_merce").isJsonNull()) && !jsonObj.get("valore_merce").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `valore_merce` to be a primitive type in the JSON string but got `%s`", jsonObj.get("valore_merce").toString()));
      }
      if ((jsonObj.get("numero_aut") != null && !jsonObj.get("numero_aut").isJsonNull()) && !jsonObj.get("numero_aut").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `numero_aut` to be a primitive type in the JSON string but got `%s`", jsonObj.get("numero_aut").toString()));
      }
      if ((jsonObj.get("paese_comunitario") != null && !jsonObj.get("paese_comunitario").isJsonNull()) && !jsonObj.get("paese_comunitario").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `paese_comunitario` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paese_comunitario").toString()));
      }
      if ((jsonObj.get("produzione") != null && !jsonObj.get("produzione").isJsonNull()) && !jsonObj.get("produzione").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `produzione` to be a primitive type in the JSON string but got `%s`", jsonObj.get("produzione").toString()));
      }
      if ((jsonObj.get("azienda_produttrice") != null && !jsonObj.get("azienda_produttrice").isJsonNull()) && !jsonObj.get("azienda_produttrice").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `azienda_produttrice` to be a primitive type in the JSON string but got `%s`", jsonObj.get("azienda_produttrice").toString()));
      }
      if ((jsonObj.get("modifiche") != null && !jsonObj.get("modifiche").isJsonNull()) && !jsonObj.get("modifiche").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `modifiche` to be a primitive type in the JSON string but got `%s`", jsonObj.get("modifiche").toString()));
      }
      if ((jsonObj.get("azienda_modifiche") != null && !jsonObj.get("azienda_modifiche").isJsonNull()) && !jsonObj.get("azienda_modifiche").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `azienda_modifiche` to be a primitive type in the JSON string but got `%s`", jsonObj.get("azienda_modifiche").toString()));
      }
      if ((jsonObj.get("paese_extraue") != null && !jsonObj.get("paese_extraue").isJsonNull()) && !jsonObj.get("paese_extraue").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `paese_extraue` to be a primitive type in the JSON string but got `%s`", jsonObj.get("paese_extraue").toString()));
      }
      if ((jsonObj.get("documentazione_allegata") != null && !jsonObj.get("documentazione_allegata").isJsonNull()) && !jsonObj.get("documentazione_allegata").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `documentazione_allegata` to be a primitive type in the JSON string but got `%s`", jsonObj.get("documentazione_allegata").toString()));
      }
      if ((jsonObj.get("giacenza_merci") != null && !jsonObj.get("giacenza_merci").isJsonNull()) && !jsonObj.get("giacenza_merci").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `giacenza_merci` to be a primitive type in the JSON string but got `%s`", jsonObj.get("giacenza_merci").toString()));
      }
      if ((jsonObj.get("annotazioni_mittente") != null && !jsonObj.get("annotazioni_mittente").isJsonNull()) && !jsonObj.get("annotazioni_mittente").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `annotazioni_mittente` to be a primitive type in the JSON string but got `%s`", jsonObj.get("annotazioni_mittente").toString()));
      }
      if ((jsonObj.get("annotazioni_interne") != null && !jsonObj.get("annotazioni_interne").isJsonNull()) && !jsonObj.get("annotazioni_interne").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `annotazioni_interne` to be a primitive type in the JSON string but got `%s`", jsonObj.get("annotazioni_interne").toString()));
      }
      if ((jsonObj.get("proforma") != null && !jsonObj.get("proforma").isJsonNull()) && !jsonObj.get("proforma").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `proforma` to be a primitive type in the JSON string but got `%s`", jsonObj.get("proforma").toString()));
      }
      if ((jsonObj.get("urgente") != null && !jsonObj.get("urgente").isJsonNull()) && !jsonObj.get("urgente").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `urgente` to be a primitive type in the JSON string but got `%s`", jsonObj.get("urgente").toString()));
      }
      if ((jsonObj.get("email_contatto") != null && !jsonObj.get("email_contatto").isJsonNull()) && !jsonObj.get("email_contatto").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `email_contatto` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email_contatto").toString()));
      }
      // validate the optional field `cciaa`
      if (jsonObj.get("cciaa") != null && !jsonObj.get("cciaa").isJsonNull()) {
        V2richiesteStoreRequestCciaa.validateJsonElement(jsonObj.get("cciaa"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V2richiesteUpdateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V2richiesteUpdateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V2richiesteUpdateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V2richiesteUpdateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<V2richiesteUpdateRequest>() {
           @Override
           public void write(JsonWriter out, V2richiesteUpdateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public V2richiesteUpdateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             V2richiesteUpdateRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of V2richiesteUpdateRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of V2richiesteUpdateRequest
   * @throws IOException if the JSON string is invalid with respect to V2richiesteUpdateRequest
   */
  public static V2richiesteUpdateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V2richiesteUpdateRequest.class);
  }

  /**
   * Convert an instance of V2richiesteUpdateRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

