/*
 * API Sprint - Documentazione
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * V2richiesteStoreRequestCciaa
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-31T09:52:59.357933300+02:00[Europe/Rome]", comments = "Generator version: 7.21.0")
public class V2richiesteStoreRequestCciaa {
  public static final String SERIALIZED_NAME_SPORTELLO = "sportello";
  @SerializedName(SERIALIZED_NAME_SPORTELLO)
  @javax.annotation.Nullable
  private String sportello;

  public static final String SERIALIZED_NAME_SEDE = "sede";
  @SerializedName(SERIALIZED_NAME_SEDE)
  @javax.annotation.Nullable
  private String sede;

  public V2richiesteStoreRequestCciaa() {
  }

  public V2richiesteStoreRequestCciaa sportello(@javax.annotation.Nullable String sportello) {
    this.sportello = sportello;
    return this;
  }

  /**
   * Get sportello
   * @return sportello
   */
  @javax.annotation.Nullable
  public String getSportello() {
    return sportello;
  }

  public void setSportello(@javax.annotation.Nullable String sportello) {
    this.sportello = sportello;
  }


  public V2richiesteStoreRequestCciaa sede(@javax.annotation.Nullable String sede) {
    this.sede = sede;
    return this;
  }

  /**
   * Get sede
   * @return sede
   */
  @javax.annotation.Nullable
  public String getSede() {
    return sede;
  }

  public void setSede(@javax.annotation.Nullable String sede) {
    this.sede = sede;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2richiesteStoreRequestCciaa v2richiesteStoreRequestCciaa = (V2richiesteStoreRequestCciaa) o;
    return Objects.equals(this.sportello, v2richiesteStoreRequestCciaa.sportello) &&
        Objects.equals(this.sede, v2richiesteStoreRequestCciaa.sede);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sportello, sede);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2richiesteStoreRequestCciaa {\n");
    sb.append("    sportello: ").append(toIndentedString(sportello)).append("\n");
    sb.append("    sede: ").append(toIndentedString(sede)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("sportello", "sede"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to V2richiesteStoreRequestCciaa
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V2richiesteStoreRequestCciaa.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in V2richiesteStoreRequestCciaa is not found in the empty JSON string", V2richiesteStoreRequestCciaa.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!V2richiesteStoreRequestCciaa.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `V2richiesteStoreRequestCciaa` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("sportello") != null && !jsonObj.get("sportello").isJsonNull()) && !jsonObj.get("sportello").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sportello` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sportello").toString()));
      }
      if ((jsonObj.get("sede") != null && !jsonObj.get("sede").isJsonNull()) && !jsonObj.get("sede").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sede` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sede").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V2richiesteStoreRequestCciaa.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V2richiesteStoreRequestCciaa' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V2richiesteStoreRequestCciaa> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V2richiesteStoreRequestCciaa.class));

       return (TypeAdapter<T>) new TypeAdapter<V2richiesteStoreRequestCciaa>() {
           @Override
           public void write(JsonWriter out, V2richiesteStoreRequestCciaa value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public V2richiesteStoreRequestCciaa read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of V2richiesteStoreRequestCciaa given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of V2richiesteStoreRequestCciaa
   * @throws IOException if the JSON string is invalid with respect to V2richiesteStoreRequestCciaa
   */
  public static V2richiesteStoreRequestCciaa fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V2richiesteStoreRequestCciaa.class);
  }

  /**
   * Convert an instance of V2richiesteStoreRequestCciaa to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

