/*
 * API Sprint - Documentazione
 * IBSWebCO API Sprint per l'automazione delle richieste di Certificati di origine e Visti alle Camera di commercio italiane (servizio Commercio Estero)
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import it.ibswebco.sprint.JSON;

/**
 * V2vistiUpdateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-02T09:24:48.820213600+02:00[Europe/Rome]", comments = "Generator version: 7.21.0")
public class V2vistiUpdateRequest {
  public static final String SERIALIZED_NAME_DESCRIZIONE = "descrizione";
  @SerializedName(SERIALIZED_NAME_DESCRIZIONE)
  @javax.annotation.Nonnull
  private String descrizione;

  public static final String SERIALIZED_NAME_ANNOTAZIONI_MITTENTE = "annotazioni_mittente";
  @SerializedName(SERIALIZED_NAME_ANNOTAZIONI_MITTENTE)
  @javax.annotation.Nullable
  private String annotazioniMittente;

  public static final String SERIALIZED_NAME_STAMPA_AZIENDA = "stampa_azienda";
  @SerializedName(SERIALIZED_NAME_STAMPA_AZIENDA)
  @javax.annotation.Nullable
  private String stampaAzienda;

  public V2vistiUpdateRequest() {
  }

  public V2vistiUpdateRequest descrizione(@javax.annotation.Nonnull String descrizione) {
    this.descrizione = descrizione;
    return this;
  }

  /**
   * Get descrizione
   * @return descrizione
   */
  @javax.annotation.Nonnull
  public String getDescrizione() {
    return descrizione;
  }

  public void setDescrizione(@javax.annotation.Nonnull String descrizione) {
    this.descrizione = descrizione;
  }


  public V2vistiUpdateRequest annotazioniMittente(@javax.annotation.Nullable String annotazioniMittente) {
    this.annotazioniMittente = annotazioniMittente;
    return this;
  }

  /**
   * Get annotazioniMittente
   * @return annotazioniMittente
   */
  @javax.annotation.Nullable
  public String getAnnotazioniMittente() {
    return annotazioniMittente;
  }

  public void setAnnotazioniMittente(@javax.annotation.Nullable String annotazioniMittente) {
    this.annotazioniMittente = annotazioniMittente;
  }


  public V2vistiUpdateRequest stampaAzienda(@javax.annotation.Nullable String stampaAzienda) {
    this.stampaAzienda = stampaAzienda;
    return this;
  }

  /**
   * Get stampaAzienda
   * @return stampaAzienda
   */
  @javax.annotation.Nullable
  public String getStampaAzienda() {
    return stampaAzienda;
  }

  public void setStampaAzienda(@javax.annotation.Nullable String stampaAzienda) {
    this.stampaAzienda = stampaAzienda;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the V2vistiUpdateRequest instance itself
   */
  public V2vistiUpdateRequest putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V2vistiUpdateRequest v2vistiUpdateRequest = (V2vistiUpdateRequest) o;
    return Objects.equals(this.descrizione, v2vistiUpdateRequest.descrizione) &&
        Objects.equals(this.annotazioniMittente, v2vistiUpdateRequest.annotazioniMittente) &&
        Objects.equals(this.stampaAzienda, v2vistiUpdateRequest.stampaAzienda)&&
        Objects.equals(this.additionalProperties, v2vistiUpdateRequest.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(descrizione, annotazioniMittente, stampaAzienda, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V2vistiUpdateRequest {\n");
    sb.append("    descrizione: ").append(toIndentedString(descrizione)).append("\n");
    sb.append("    annotazioniMittente: ").append(toIndentedString(annotazioniMittente)).append("\n");
    sb.append("    stampaAzienda: ").append(toIndentedString(stampaAzienda)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("descrizione", "annotazioni_mittente", "stampa_azienda"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("descrizione"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to V2vistiUpdateRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!V2vistiUpdateRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in V2vistiUpdateRequest is not found in the empty JSON string", V2vistiUpdateRequest.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : V2vistiUpdateRequest.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("descrizione").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `descrizione` to be a primitive type in the JSON string but got `%s`", jsonObj.get("descrizione").toString()));
      }
      if ((jsonObj.get("annotazioni_mittente") != null && !jsonObj.get("annotazioni_mittente").isJsonNull()) && !jsonObj.get("annotazioni_mittente").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `annotazioni_mittente` to be a primitive type in the JSON string but got `%s`", jsonObj.get("annotazioni_mittente").toString()));
      }
      if ((jsonObj.get("stampa_azienda") != null && !jsonObj.get("stampa_azienda").isJsonNull()) && !jsonObj.get("stampa_azienda").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `stampa_azienda` to be a primitive type in the JSON string but got `%s`", jsonObj.get("stampa_azienda").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!V2vistiUpdateRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'V2vistiUpdateRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<V2vistiUpdateRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(V2vistiUpdateRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<V2vistiUpdateRequest>() {
           @Override
           public void write(JsonWriter out, V2vistiUpdateRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public V2vistiUpdateRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             V2vistiUpdateRequest instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of V2vistiUpdateRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of V2vistiUpdateRequest
   * @throws IOException if the JSON string is invalid with respect to V2vistiUpdateRequest
   */
  public static V2vistiUpdateRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, V2vistiUpdateRequest.class);
  }

  /**
   * Convert an instance of V2vistiUpdateRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

